spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  #    properties:
#      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
#    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/ruoyi-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    # 应用名称
    name: lb-management
#  profiles:
#    # 环境配置
#    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
#      config:
#        # 配置中心地址
#        server-addr: 127.0.0.1:8848
#        # 配置文件格式
#        file-extension: yml
#        # 共享配置
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
server:
  port: 8800
logging:
  level:
    xyz.qumn.lb: trace
    org.hibernate.type: trace
    org.hibernate.SQL: trace